//> using scala 3.6.3
//> using dep io.github.bishabosha::upickle-nt::0.1.0-SNAPSHOT
//> using dep io.github.bishabosha::query-nt::0.1.2-SNAPSHOT
//> using dep io.github.bishabosha::endpoints-nt-core::0.1.0-SNAPSHOT
//> using dep io.github.bishabosha::endpoints-nt-jdkhttp::0.1.1-SNAPSHOT
//> using dep io.github.bishabosha::endpoints-nt-jdkhttp-upickle::0.1.1-SNAPSHOT
//> using dep io.github.bishabosha::example-full-stack-app-nt-core::0.1.0-SNAPSHOT
//> using dep com.lihaoyi::upickle::4.1.0
//> using options -language:experimental.namedTuples
