//> using scala 3.6.3
//> using jsVersion 1.18.0
//> using platform scala-js
//> using dep io.github.bishabosha::upickle-nt::0.1.0-SNAPSHOT
//> using dep io.github.bishabosha::endpoints-nt-core::0.1.0-SNAPSHOT
//> using dep io.github.bishabosha::endpoints-nt-fetchhttp::0.1.1-SNAPSHOT
//> using dep io.github.bishabosha::example-full-stack-app-nt-core::0.1.0-SNAPSHOT
//> using dep com.raquo::laminar::17.2.0
//> using dep com.lihaoyi::upickle::4.1.0
//> using dep org.scala-js::scalajs-dom::2.8.0
//> using options -language:experimental.namedTuples
