publishLocal:
	scala --power publish local . --organization io.github.bishabosha --name endpoints-nt-core --project-version $(shell cat .project-version)
	scala --power publish local . --js --organization io.github.bishabosha --name endpoints-nt-core --project-version $(shell cat .project-version)
